name: Release

on:
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch full history, so changelog can be generated
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn run ci

      - run: yarn run lint
      - run: yarn run test

      - run: yarn run build

      - run: yarn run test-types
      - run: yarn run size

      - name: git config
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: yarn run typedoc
      - name: commit docs website
        run: |
          git add docs
          git diff-index --quiet HEAD || git commit -m 'docs: update docs website'

      - run: yarn run release

      - run: yarn run generate-compatibility
      - name: commit compatibility table
        run: |
          git add compatibility.md
          git diff-index --quiet HEAD || git commit -m 'docs: update compatibility table'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
